<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>g2bot_bringup</name>
  <version>0.0.0</version>
  <description>G2 (genie) 机器人启动包（占位，对应 gzbot_bringup 的职责）</description>
  <maintainer email="1175533636@qq.com">gz</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <exec_depend>g2bot_description</exec_depend>
  <exec_depend>g2bot_gazebo</exec_depend>
  <exec_depend>g2bot_moveit_config</exec_depend>

  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
